### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'avconv'

### ISSUE THREAD

**Issue by sajumani** [chaonan99/ppt_presenter#2]
When i run 

> sudo python ppt_presenter.py --pptx test.pptx --pdf test.pdf -o test.mp4

Am getting following error;

Traceback (most recent call last):
  File "ppt_presenter.py", line 71, in <module>
    main()
  File "ppt_presenter.py", line 67, in main
    ppt_presenter(args.pptx, args.pdf, args.output)
  File "ppt_presenter.py", line 38, in ppt_presenter
    ffmpeg_call(image_path, audio_path, temp_path, i)
  File "ppt_presenter.py", line 51, in ffmpeg_call
    '-b:a', '192k', '-pix_fmt', 'yuv420p', '-shortest', out_path_mp4])
  File "/usr/local/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'avconv'

**Comment by sajumani** [comment]
It was solved by below comments:

**Install OKey repository:**

> # yum install http://repo.okay.com.mx/centos/7/x86_64/release/okay-release-1-1.noarch.rpm
> Install libav-tools rpm package:
> # yum install libav-tools
