### ISSUE TITLE
AttributeError: 'module' object has no attribute 'TemporaryDirectory'

### ISSUE THREAD

**Issue by PatelBassar** [chaonan99/ppt_presenter#5]
I am getting Error as below.
AttributeError: 'module' object has no attribute 'TemporaryDirectory'

**Comment by chaonan99** [comment]
What's the full traceback?

**Comment by PatelBassar** [comment]
Traceback (most recent call last):
  File "ppt_presenter.py", line 71, in <module>
    main()
  File "ppt_presenter.py", line 67, in main
    ppt_presenter(args.pptx, args.pdf, args.output)
  File "ppt_presenter.py", line 24, in ppt_presenter
    with tempfile.TemporaryDirectory() as temp_path:
AttributeError: 'module' object has no attribute 'TemporaryDirectory'

**Comment by PatelBassar** [comment]
Traceback (most recent call last):
  File "ppt_presenter.py", line 71, in <module>
    main()
  File "ppt_presenter.py", line 67, in main
    ppt_presenter(args.pptx, args.pdf, args.output)
  File "ppt_presenter.py", line 24, in ppt_presenter
    with tempfile.TemporaryDirectory() as temp_path:
AttributeError: 'module' object has no attribute 'TemporaryDirectory'

**Comment by chaonan99** [comment]
Looks like you are using python 2. You can try to change `TemporaryDirectory ` to `tempdir`: https://docs.python.org/2/library/tempfile.html

**Comment by PatelBassar** [comment]
Traceback (most recent call last):
  File "ppt_presenter.py", line 71, in <module>
    main()
  File "ppt_presenter.py", line 67, in main
    ppt_presenter(args.pptx, args.pdf, args.output)
  File "ppt_presenter.py", line 24, in ppt_presenter
    with tempfile.tempdir() as temp_path:
TypeError: 'NoneType' object is not callable
